import Head from '../../node_modules/next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Image from '../../node_modules/react-bootstrap/esm/Image'
import cashierTop from '../components/Cashiers'
import Cashiers from '../components/Cashiers'

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
        <div className={styles.ground}>
          <div className="flex items-center h-full justify-center">
            <div className="text-center text-slate-200">
              <h1 className="text-7xl">CONQUER</h1>
              <p className="text-xl">Simple tailwindcss Template</p>
            </div>
          </div>
        </div>
      </header>
      <main>
        <div className={styles.cashiers}>
           <Cashiers 
           subTitle="Bootstrap v3.3.6"
           text="Morbi sagittis justo a velit placerat ullamcorper quis quis
            velit. Sed convallis at risus ullamcorper auctor. Praesent quis 
            velit neque. Quisque semper porta nisi vitae suscipit. Duis 
            lectus magna, ornare ac scelerisque."
           />

           
        </div>
      </main>
      
    </div>


  )
}
