import Head from "../../node_modules/next/head"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Clone tamplete</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
    </div>
  )
}
