import Head from "next/head"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Clone tamplete</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate non deserunt obcaecati culpa, nihil reiciendis dignissimos odio, asperiores tempore, ipsum tenetur quasi. Est eaque exercitationem laborum, nemo animi numquam quia?</p>
     
    </div>
  )
}
