import Head from '../../node_modules/next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Image from '../../node_modules/react-bootstrap/esm/Image'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
        <div className={styles.ground}>
          <div className="flex items-center h-full justify-center">
            <div className="text-center text-slate-200">
              <h1 className="text-7xl">CONQUER</h1>
              <p className="text-xl">Simple tailwindcss Template</p>
            </div>
          </div>
        </div>

      </header>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum vel, iure quasi aperiam consectetur assumenda. Magni nesciunt cupiditate officiis molestiae labore. Ad eos quod facere vitae provident maiores perferendis explicabo?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum vel, iure quasi aperiam consectetur assumenda. Magni nesciunt cupiditate officiis molestiae labore. Ad eos quod facere vitae provident maiores perferendis explicabo?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum vel, iure quasi aperiam consectetur assumenda. Magni nesciunt cupiditate officiis molestiae labore. Ad eos quod facere vitae provident maiores perferendis explicabo?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum vel, iure quasi aperiam consectetur assumenda. Magni nesciunt cupiditate officiis molestiae labore. Ad eos quod facere vitae provident maiores perferendis explicabo?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum vel, iure quasi aperiam consectetur assumenda. Magni nesciunt cupiditate officiis molestiae labore. Ad eos quod facere vitae provident maiores perferendis explicabo?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum vel, iure quasi aperiam consectetur assumenda. Magni nesciunt cupiditate officiis molestiae labore. Ad eos quod facere vitae provident maiores perferendis explicabo?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum vel, iure quasi aperiam consectetur assumenda. Magni nesciunt cupiditate officiis molestiae labore. Ad eos quod facere vitae provident maiores perferendis explicabo?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum vel, iure quasi aperiam consectetur assumenda. Magni nesciunt cupiditate officiis molestiae labore. Ad eos quod facere vitae provident maiores perferendis explicabo?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum vel, iure quasi aperiam consectetur assumenda. Magni nesciunt cupiditate officiis molestiae labore. Ad eos quod facere vitae provident maiores perferendis explicabo?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum vel, iure quasi aperiam consectetur assumenda. Magni nesciunt cupiditate officiis molestiae labore. Ad eos quod facere vitae provident maiores perferendis explicabo?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum vel, iure quasi aperiam consectetur assumenda. Magni nesciunt cupiditate officiis molestiae labore. Ad eos quod facere vitae provident maiores perferendis explicabo?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum vel, iure quasi aperiam consectetur assumenda. Magni nesciunt cupiditate officiis molestiae labore. Ad eos quod facere vitae provident maiores perferendis explicabo?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum vel, iure quasi aperiam consectetur assumenda. Magni nesciunt cupiditate officiis molestiae labore. Ad eos quod facere vitae provident maiores perferendis explicabo?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum vel, iure quasi aperiam consectetur assumenda. Magni nesciunt cupiditate officiis molestiae labore. Ad eos quod facere vitae provident maiores perferendis explicabo?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum vel, iure quasi aperiam consectetur assumenda. Magni nesciunt cupiditate officiis molestiae labore. Ad eos quod facere vitae provident maiores perferendis explicabo?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum vel, iure quasi aperiam consectetur assumenda. Magni nesciunt cupiditate officiis molestiae labore. Ad eos quod facere vitae provident maiores perferendis explicabo?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum vel, iure quasi aperiam consectetur assumenda. Magni nesciunt cupiditate officiis molestiae labore. Ad eos quod facere vitae provident maiores perferendis explicabo?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum vel, iure quasi aperiam consectetur assumenda. Magni nesciunt cupiditate officiis molestiae labore. Ad eos quod facere vitae provident maiores perferendis explicabo?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum vel, iure quasi aperiam consectetur assumenda. Magni nesciunt cupiditate officiis molestiae labore. Ad eos quod facere vitae provident maiores perferendis explicabo?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum vel, iure quasi aperiam consectetur assumenda. Magni nesciunt cupiditate officiis molestiae labore. Ad eos quod facere vitae provident maiores perferendis explicabo?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum vel, iure quasi aperiam consectetur assumenda. Magni nesciunt cupiditate officiis molestiae labore. Ad eos quod facere vitae provident maiores perferendis explicabo?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum vel, iure quasi aperiam consectetur assumenda. Magni nesciunt cupiditate officiis molestiae labore. Ad eos quod facere vitae provident maiores perferendis explicabo?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum vel, iure quasi aperiam consectetur assumenda. Magni nesciunt cupiditate officiis molestiae labore. Ad eos quod facere vitae provident maiores perferendis explicabo?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum vel, iure quasi aperiam consectetur assumenda. Magni nesciunt cupiditate officiis molestiae labore. Ad eos quod facere vitae provident maiores perferendis explicabo?</p>
    </div>


  )
}
