import Head from "next/head"
import Hero from '../components/Hero'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Clone tamplete</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
         <Hero heading="COUQUER" message="Simple Tailwindcss Template next"></Hero>
      </header>
    </div>
  )
}
